apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.opendi.com_gatewayhostnamerequests.yaml
  - gateway.opendi.com_domainclaims.yaml
  - gateway.opendi.com_hostnamegrants.yaml
