apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-orchestrator-system

resources:
  - ../../default

images:
  - name: gateway-orchestrator
    newName: ghcr.io/mfeldheim/gateway-orchestrator
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "eu-central-1"
    target:
      kind: Deployment
      name: gateway-orchestrator-controller
